### ISSUE TITLE
Partial Result from Starred Notes

### ISSUE THREAD

**Issue by gintonyc** [KevinBatdorf/obsidian-raycast#58] opened 2023-06-06 10:53 UTC
Hi, it seems that the _starred notes_ command displays partial results on my mac.

This is the bookmark (used to be _starred_) section on my obsidian.
<img width="284" alt="Screenshot 2023-06-06 at 6 48 18 PM" src="https://github.com/KevinBatdorf/obsidian-raycast/assets/60953182/f9504c20-cb0f-419a-ba28-b8e7f7f9586a">

And this is the result from the _starred notes_ command (no search term)
<img width="749" alt="Screenshot 2023-06-06 at 6 48 58 PM" src="https://github.com/KevinBatdorf/obsidian-raycast/assets/60953182/88124923-8770-4c70-98ed-daecdb031f8e">

- I've tried to reload the notes in the extension setting, nothing changed.
- Originally there were three notes shown in the _starred notes_ command result, I unstarred one of them from raycast but the change didn't apply in obsidian.

Great extension by the way. And thanks in advance for help.

**Comment by gintonyc** [comment] 2023-06-08 02:27
The first question I wanna figure out is whether I'm the only one having this issue. If so I would try uninstalling obsidian/raycast obsidian.

Some specs:
- macos: 13.2.1 (22D68)
- obsidian: 13.2.1 (22D68)
    - vault located in icloud drive
- raycast: 1.52.1

**Comment by KevinBatdorf** [comment] 2023-06-08 02:35
Hey, sorry for the late reply. Been a busy week. Let me investigate this tomorrow. I've actually only recently started maintaining this repo so I may be a little slow to catch up. 

I'll try to reproduce it based on your description above, but to summarize, is it accurate that you have additional starred items that you expect should be showing up that arent there?

What if you add a new one now? Does that one show up?

**Comment by gintonyc** [comment] 2023-06-08 02:43
Hey Kevin, thanks for the reply. And no worries, it's an open source project and I'm always grateful for your effort. Take your time.

Your summarization is accurate. And newly starred item won't show up in raycast obsidian.

**Comment by KevinBatdorf** [comment] 2023-06-09 00:50
So as you mentioned, it looks like Obsidian replaced the starred functionality with bookmarks just last month. I should have time this weekend to update the code to match their new api. I'll reply here with an update after that.

https://forum.obsidian.md/t/obsidian-release-v1-2-7/59004

Thanks for reporting it too as I wasn't using that feature and just missed it.

**Comment by KevinBatdorf** [comment] 2023-06-10 23:33
PR here: https://github.com/raycast/extensions/pull/7031

Thanks again. I'll close this but if something is off just reopen or star a new issue.

**Closed by KevinBatdorf** 2023-06-10 23:33 UTC
